language: elixir
matrix:
  include:
  - elixir: 1.6
    otp_release: 21.0
  - elixir: 1.7
    otp_release: 22.0
  - elixir: 1.8
    otp_release: 22.0
  - elixir: 1.9
    otp_release: 22.0
  - elixir: 1.1
    otp_release: 22.0
before_install:
- openssl aes-256-cbc -K $encrypted_3033c569c247_key -iv $encrypted_3033c569c247_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script:
- MIX_ENV=test mix do deps.get, compile, coveralls.travis
