language: elixir
elixir:
  - 1.4.5
  - 1.5.1
otp_release:
  - 19.2
  - 20.0
before_install:
- openssl aes-256-cbc -K $encrypted_3033c569c247_key -iv
  $encrypted_3033c569c247_iv -in cert_key.tar.enc -out
  cert_key.tar -d
- tar xvf cert_key.tar
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
